In [2]:
import numpy as np

In [12]:
a = np.array([[1, 2], [3, 4]])
a.ndim
a


array([[1, 2],
       [3, 4]])

In [7]:
x=np.linspace(0,2,3)
y=np.linspace(0,2,5)
y


array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [8]:
xv,yv=np.meshgrid(y,x)
yv

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.]])